name: sam_pruning
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tqdm
  - pip
  - pip:
    - timm>=0.6.0
    - transformers
    - tensorboard
    - wandb
    - scikit-learn
    - Pillow